// Global Room Instance
const room = new WebsimSocket();

const App = () => {
    const [peers, setPeers] = React.useState({});
    const [presence, setPresence] = React.useState({});
    const [currentUser, setCurrentUser] = React.useState(null);

    // User Settings
    const [threshold, setThreshold] = React.useState(500);
    const [spent, setSpent] = React.useState(0);

    // UI State
    const [tab, setTab] = React.useState('generate'); // generate | settings | leaderboard
    const [prompt, setPrompt] = React.useState("");
    const [selectedImage, setSelectedImage] = React.useState(null); // File object
    const [processingPeerId, setProcessingPeerId] = React.useState(null);
    const [resultImage, setResultImage] = React.useState(null);
    const [statusMsg, setStatusMsg] = React.useState("Ready");

    // Leaderboard Data
    const [leaderboard, setLeaderboard] = React.useState([]);

    React.useEffect(() => {
        const init = async () => {
            await room.initialize();

            // Initial presence setup
            const me = await window.websim.getCurrentUser();
            setCurrentUser(me);

            updateMyPresence(spent, threshold);

            // Subscribe to updates
            room.subscribePresence((p) => setPresence(p));

            // Subscribe to room peers (for usernames/avatars)
            // Note: In websim library, peers is updated automatically, but we can poll or trigger on presence
            const updatePeers = () => setPeers({ ...room.peers });
            updatePeers();
            room.subscribePresence(updatePeers); // Peers often change when presence changes

            // Handle Incoming Messages
            room.onmessage = handleMessage;
        };
        init();
    }, []);

    // Effect to update presence when local stats change
    React.useEffect(() => {
        if (currentUser) {
            updateMyPresence(spent, threshold);
        }
    }, [spent, threshold]);

    // Refresh leaderboard when switching to that tab
    React.useEffect(() => {
        if (tab === 'leaderboard') {
            fetchLeaderboard();
        }
    }, [tab]);

    const updateMyPresence = (currentSpent, currentThreshold) => {
        const isAccepting = currentSpent < currentThreshold;
        room.updatePresence({
            spent: currentSpent,
            threshold: currentThreshold,
            accepting: isAccepting
        });
    };

    const handleMessage = async (event) => {
        const { type, data } = event;
        // Logic for the Receiver (The one processing requests)
        if (type === 'REQUEST_GENERATION' && data.targetId === room.clientId) {
            await processRequest(data);
        }

        // Logic for the Sender (The one receiving results)
        if (type === 'GENERATION_COMPLETE' && data.targetId === room.clientId) {
            setProcessingPeerId(null);
            if (data.success) {
                setResultImage(data.imageUrl);
                setStatusMsg(`Generated by ${data.processorName}!`);
            } else {
                setStatusMsg(`Error from ${data.processorName}: ${data.error}`);
            }
        }
    };

    // --- The Core "Server" Logic (Runs on client) ---
    const processRequest = async (requestData) => {
        const COST = 100;

        // Double check limits
        if (spent + COST > threshold) {
            room.send({
                type: 'GENERATION_COMPLETE',
                targetId: requestData.senderId,
                success: false,
                error: "Processor hit credit limit."
            });
            return;
        }

        try {
            // Update status to peers (optional: busy state)
            room.updatePresence({ ...room.presence[room.clientId], status: 'generating' });

            const options = {
                prompt: requestData.prompt,
                width: 1024,
                height: 1024,
            };

            if (requestData.sourceImageUrl) {
                options.image_inputs = [{ url: requestData.sourceImageUrl }];
            }

            // Call AI
            const result = await websim.imageGen(options);

            // Update local spent amount
            const newSpent = spent + COST;
            setSpent(newSpent);

            // Log to Database (User's single row)
            await logJobToDatabase(requestData, result.url);

            // Send Result back
            room.send({
                type: 'GENERATION_COMPLETE',
                targetId: requestData.senderId,
                processorName: room.peers[room.clientId].username,
                success: true,
                imageUrl: result.url
            });

        } catch (err) {
            console.error(err);
            room.send({
                type: 'GENERATION_COMPLETE',
                targetId: requestData.senderId,
                processorName: room.peers[room.clientId].username,
                success: false,
                error: "Generation failed."
            });
        } finally {
            room.updatePresence({
                ...room.presence[room.clientId],
                status: 'idle',
                spent: spent + COST // Ensure presence reflects new spent
            });
        }
    };

    const logJobToDatabase = async (reqData, resultUrl) => {
        const collection = room.collection('processor_stats_v1');
        const myId = room.clientId; // Or user ID. Using created_by filter is safest.

        // Find my existing record
        const records = await collection.filter({ created_by: true }).getList();

        const jobLog = {
            timestamp: new Date().toISOString(),
            requested_by: reqData.senderName,
            result_url: resultUrl,
            cost: 100
        };

        if (records.length > 0) {
            const record = records[0];
            // Append to existing logs. 
            // Note: JSON fields in some DBs have limits, but for this demo we append to a JSON array.
            let logs = [];
            try {
                logs = record.logs ? (typeof record.logs === 'string' ? JSON.parse(record.logs) : record.logs) : [];
            } catch (e) { logs = [] }

            logs.push(jobLog);

            await collection.update(record.id, {
                logs: JSON.stringify(logs),
                total_processed: (record.total_processed || 0) + 1
            });
        } else {
            await collection.create({
                logs: JSON.stringify([jobLog]),
                total_processed: 1
            });
        }
    };

    const fetchLeaderboard = async () => {
        const records = await room.collection('processor_stats_v1').getList();
        // Sort by total_processed descending
        const sorted = records.sort((a, b) => (b.total_processed || 0) - (a.total_processed || 0));
        setLeaderboard(sorted);
    };

    // --- Client / Sender Logic ---

    const sendRequest = async (targetPeerId) => {
        if (!prompt) return alert("Please enter a prompt");

        setProcessingPeerId(targetPeerId);
        setStatusMsg("Uploading assets...");
        setResultImage(null);

        let sourceImageUrl = null;
        if (selectedImage) {
            try {
                sourceImageUrl = await websim.upload(selectedImage);
            } catch (e) {
                setStatusMsg("Upload failed.");
                setProcessingPeerId(null);
                return;
            }
        }

        setStatusMsg(`Waiting for ${peers[targetPeerId]?.username}...`);

        room.send({
            type: 'REQUEST_GENERATION',
            targetId: targetPeerId,
            senderId: room.clientId,
            senderName: currentUser.username,
            prompt: prompt,
            sourceImageUrl: sourceImageUrl
        });
    };

    const handleFileChange = (e) => {
        if (e.target.files && e.target.files[0]) {
            setSelectedImage(e.target.files[0]);
        }
    };

    // --- Render Helpers ---

    const getPeerStatus = (pid) => {
        const p = presence[pid] || {};
        if (pid === room.clientId) return { label: "(You)", valid: false };
        if (p.status === 'generating') return { label: "Busy", valid: false };
        if (p.accepting === false) return { label: "Maxed Out", valid: false };
        return { label: "Available", valid: true };
    };

    return (
        <div className="flex flex-col h-full max-w-md mx-auto w-full bg-slate-900 shadow-2xl relative">
            {/* Header */}
            <header className="p-4 bg-slate-800 border-b border-slate-700 flex justify-between items-center z-10">
                <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-600">
                    GenShare
                </h1>
                <div className="flex gap-2">
                    <button
                        onClick={() => setTab('generate')}
                        className={`px-3 py-1 rounded text-sm ${tab === 'generate' ? 'bg-purple-600 text-white' : 'text-slate-400'}`}>
                        Gen
                    </button>
                    <button
                        onClick={() => setTab('leaderboard')}
                        className={`px-3 py-1 rounded text-sm ${tab === 'leaderboard' ? 'bg-purple-600 text-white' : 'text-slate-400'}`}>
                        Top
                    </button>
                    <button
                        onClick={() => setTab('settings')}
                        className={`px-3 py-1 rounded text-sm ${tab === 'settings' ? 'bg-purple-600 text-white' : 'text-slate-400'}`}>
                        Me
                    </button>
                </div>
            </header>

            {/* Main Content Area */}
            <main className="flex-1 overflow-y-auto p-4 scroll-container relative">

                {/* SETTINGS TAB */}
                {tab === 'settings' && (
                    <div className="space-y-6 animate-fade-in">
                        <div className="bg-slate-800 p-6 rounded-xl border border-slate-700">
                            <div className="flex items-center gap-4 mb-4">
                                <img src={currentUser?.avatarUrl} className="w-16 h-16 rounded-full border-2 border-purple-500" />
                                <div>
                                    <h2 className="text-xl font-bold">{currentUser?.username}</h2>
                                    <p className="text-slate-400 text-sm">Credit Provider</p>
                                </div>
                            </div>

                            <div className="space-y-4">
                                <div>
                                    <label className="block text-sm text-slate-400 mb-1">Session Limit (Credits)</label>
                                    <input
                                        type="number"
                                        value={threshold}
                                        onChange={(e) => setThreshold(Number(e.target.value))}
                                        className="w-full bg-slate-900 border border-slate-700 rounded p-2 text-white focus:border-purple-500 outline-none"
                                    />
                                    <p className="text-xs text-slate-500 mt-1">100 Credits per generation</p>
                                </div>

                                <div className="p-4 bg-slate-900 rounded-lg">
                                    <div className="flex justify-between mb-2">
                                        <span className="text-slate-300">Credits Spent</span>
                                        <span className="font-mono text-purple-400">{spent} / {threshold}</span>
                                    </div>
                                    <div className="w-full bg-slate-700 h-2 rounded-full overflow-hidden">
                                        <div
                                            className={`h-full ${spent >= threshold ? 'bg-red-500' : 'bg-green-500'}`}
                                            style={{ width: `${Math.min((spent / threshold) * 100, 100)}%` }}
                                        ></div>
                                    </div>
                                    <div className="mt-2 text-xs text-center">
                                        {spent >= threshold
                                            ? <span className="text-red-400">You are currently rejecting requests</span>
                                            : <span className="text-green-400">You are accepting requests</span>
                                        }
                                    </div>
                                </div>

                                <button
                                    onClick={() => setSpent(0)}
                                    className="w-full py-2 border border-slate-600 rounded hover:bg-slate-700 text-sm transition-colors"
                                >
                                    Reset Session Counter
                                </button>
                            </div>
                        </div>
                    </div>
                )}

                {/* LEADERBOARD TAB */}
                {tab === 'leaderboard' && (
                    <div className="space-y-4">
                        <h2 className="text-lg font-bold text-center mb-4">Top Processors</h2>
                        {leaderboard.length === 0 ? (
                            <div className="text-center text-slate-500 py-10">Loading stats...</div>
                        ) : (
                            leaderboard.map((record, i) => (
                                <div key={record.id} className="flex items-center gap-4 bg-slate-800 p-3 rounded-lg border border-slate-700">
                                    <div className="font-bold text-2xl text-slate-600 w-8 text-center">#{i + 1}</div>
                                    <img
                                        src={`https://images.websim.com/avatar/${record.username}`}
                                        className="w-10 h-10 rounded-full bg-slate-700"
                                        onError={(e) => e.target.src = 'https://via.placeholder.com/40'}
                                    />
                                    <div className="flex-1">
                                        <div className="font-bold">{record.username}</div>
                                        <div className="text-xs text-slate-400">Processed: {record.total_processed} reqs</div>
                                    </div>
                                    <div className="text-purple-400 font-mono text-sm">
                                        {record.total_processed * 100} Cr
                                    </div>
                                </div>
                            ))
                        )}
                    </div>
                )}

                {/* GENERATE TAB */}
                {tab === 'generate' && (
                    <div className="space-y-4 pb-20">
                        {/* Result Area */}
                        <div className="min-h-[200px] bg-black/40 rounded-xl flex items-center justify-center border border-slate-700 overflow-hidden relative group">
                            {resultImage ? (
                                <div className="relative w-full h-full">
                                    <img src={resultImage} className="w-full h-auto object-contain max-h-[400px]" />
                                    <a
                                        href={resultImage}
                                        download="generated.png"
                                        className="absolute bottom-2 right-2 bg-slate-900/80 p-2 rounded text-white text-xs opacity-0 group-hover:opacity-100 transition-opacity"
                                    >
                                        Download
                                    </a>
                                </div>
                            ) : (
                                <div className="text-slate-500 text-center p-4">
                                    {processingPeerId ? (
                                        <div className="flex flex-col items-center gap-2">
                                            <div className="loader"></div>
                                            <span className="text-sm animate-pulse">{statusMsg}</span>
                                        </div>
                                    ) : (
                                        <div className="flex flex-col items-center">
                                            <span className="text-4xl mb-2">🎨</span>
                                            <span>Image will appear here</span>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>

                        {/* Inputs */}
                        <div className="bg-slate-800 p-4 rounded-xl border border-slate-700 space-y-3">
                            <textarea
                                value={prompt}
                                onChange={(e) => setPrompt(e.target.value)}
                                placeholder="Describe your image..."
                                className="w-full bg-slate-900 border border-slate-700 rounded p-3 text-white focus:border-purple-500 outline-none resize-none h-24"
                                disabled={!!processingPeerId}
                            />

                            <div className="flex items-center gap-2">
                                <label className="flex-1 bg-slate-900 hover:bg-slate-700 border border-slate-700 text-slate-300 text-sm py-2 px-4 rounded cursor-pointer transition-colors flex items-center justify-center gap-2">
                                    <span>{selectedImage ? "Change Image" : "Upload Img2Img (Optional)"}</span>
                                    <input
                                        type="file"
                                        accept="image/*"
                                        onChange={handleFileChange}
                                        className="hidden"
                                        disabled={!!processingPeerId}
                                    />
                                </label>
                                {selectedImage && (
                                    <button
                                        onClick={() => setSelectedImage(null)}
                                        className="bg-red-900/50 hover:bg-red-900 text-red-200 p-2 rounded border border-red-800"
                                    >
                                        ✕
                                    </button>
                                )}
                            </div>
                            {selectedImage && (
                                <div className="text-xs text-green-400 text-center truncate px-2">
                                    {selectedImage.name}
                                </div>
                            )}
                        </div>

                        {/* Peer Selector */}
                        <div>
                            <h3 className="text-sm font-bold text-slate-400 mb-2 uppercase tracking-wider">Select Processor (100 Cr)</h3>
                            <div className="grid grid-cols-1 gap-2">
                                {Object.values(peers).map((peer) => {
                                    if (peer.id === room.clientId) return null; // Don't show self
                                    const status = getPeerStatus(peer.id);

                                    return (
                                        <button
                                            key={peer.id}
                                            disabled={!status.valid || !!processingPeerId}
                                            onClick={() => sendRequest(peer.id)}
                                            className={`peer-card flex items-center justify-between p-3 rounded-lg border border-slate-700 bg-slate-800 text-left ${!status.valid ? 'disabled' : ''}`}
                                        >
                                            <div className="flex items-center gap-3">
                                                <div className="relative">
                                                    <img src={peer.avatarUrl} className="w-10 h-10 rounded-full bg-slate-700" />
                                                    <div className={`absolute -bottom-1 -right-1 w-3 h-3 rounded-full border-2 border-slate-800 ${status.valid ? 'bg-green-500' : 'bg-slate-500'}`}></div>
                                                </div>
                                                <div>
                                                    <div className="font-semibold text-sm">{peer.username}</div>
                                                    <div className="text-xs text-slate-400">{status.label}</div>
                                                </div>
                                            </div>
                                            {status.valid && (
                                                <div className="bg-purple-600/20 text-purple-300 text-xs px-2 py-1 rounded font-mono">
                                                    REQ
                                                </div>
                                            )}
                                        </button>
                                    );
                                })}

                                {Object.values(peers).length <= 1 && (
                                    <div className="text-center py-8 text-slate-500 text-sm border-2 border-dashed border-slate-700 rounded-lg">
                                        Waiting for other users to join...<br />
                                        <span className="text-xs opacity-70">Open this URL in a new tab to test!</span>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                )}
            </main>
        </div>
    );
};

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);