// Global Room Instance
const room = new WebsimSocket();

// Destructure components and utils from window
const { Header, SettingsTab, LeaderboardTab, GenerateTab } = window;
const { logJobToDatabase } = window.AppUtils;

const App = () => {
    const [peers, setPeers] = React.useState({});
    const [presence, setPresence] = React.useState({});
    const [currentUser, setCurrentUser] = React.useState(null);

    // User Settings
    const [threshold, setThreshold] = React.useState(500);
    const [spent, setSpent] = React.useState(0);

    // Refs for accessing latest state in callbacks
    const spentRef = React.useRef(spent);
    const thresholdRef = React.useRef(threshold);

    // UI State
    const [tab, setTab] = React.useState('generate'); // generate | settings | leaderboard
    const [prompt, setPrompt] = React.useState("");
    const [selectedImage, setSelectedImage] = React.useState(null); // File object
    const [processingPeerId, setProcessingPeerId] = React.useState(null);
    const [resultImage, setResultImage] = React.useState(null);
    const [statusMsg, setStatusMsg] = React.useState("Ready");

    // Leaderboard Data
    const [leaderboard, setLeaderboard] = React.useState([]);

    React.useEffect(() => {
        const init = async () => {
            await room.initialize();

            // Initial presence setup
            const me = await window.websim.getCurrentUser();
            setCurrentUser(me);

            updateMyPresence(spent, threshold);

            // Subscribe to updates
            room.subscribePresence((p) => setPresence(p));

            // Subscribe to room peers (for usernames/avatars)
            const updatePeers = () => setPeers({ ...room.peers });
            updatePeers();
            room.subscribePresence(updatePeers); 

            // Handle Incoming Messages
            room.onmessage = handleMessage;
        };
        init();
    }, []);

    // Effect to update presence when local stats change
    React.useEffect(() => {
        if (currentUser) {
            updateMyPresence(spent, threshold);
        }
        // Keep refs in sync
        spentRef.current = spent;
        thresholdRef.current = threshold;
    }, [spent, threshold]);

    // Refresh leaderboard when switching to that tab
    React.useEffect(() => {
        if (tab === 'leaderboard') {
            fetchLeaderboard();
        }
    }, [tab]);

    const updateMyPresence = (currentSpent, currentThreshold) => {
        const isAccepting = currentSpent < currentThreshold;
        room.updatePresence({
            spent: currentSpent,
            threshold: currentThreshold,
            accepting: isAccepting,
        });
    };

    const handleMessage = async (event) => {
        const { type, data } = event;
        // Logic for the Receiver (The one processing requests)
        if (type === 'REQUEST_GENERATION' && data.targetId === room.clientId) {
            await processRequest(data);
        }

        // Logic for the Sender (The one receiving results)
        if (type === 'GENERATION_COMPLETE' && data.targetId === room.clientId) {
            setProcessingPeerId(null);
            if (data.success) {
                setResultImage(data.imageUrl);
                setStatusMsg(`Generated by ${data.processorName}!`);
            } else {
                setStatusMsg(`Error from ${data.processorName}: ${data.error}`);
            }
        }
    };

    // --- The Core "Server" Logic (Runs on client) ---
    const processRequest = async (requestData) => {
        const COST = 100;
        const currentSpent = spentRef.current;
        const currentThreshold = thresholdRef.current;

        // Double check limits
        if (currentSpent + COST > currentThreshold) {
            const msg = {
                type: 'GENERATION_COMPLETE',
                data: {
                    targetId: requestData.senderId,
                    processorName: room.peers[room.clientId]?.username || currentUser?.username || "Unknown",
                    success: false,
                    error: "Processor hit credit limit."
                }
            };
            room.send(msg);
            if (msg.data.targetId === room.clientId) handleMessage(msg);
            return;
        }

        try {
            // Update status to peers
            room.updatePresence({ ...room.presence[room.clientId], status: 'generating' });

            const options = {
                prompt: requestData.prompt,
                width: 1024,
                height: 1024,
            };

            if (requestData.sourceImageUrl) {
                options.image_inputs = [{ url: requestData.sourceImageUrl }];
            }

            // Call AI
            const result = await websim.imageGen(options);

            // Update local spent amount
            const newSpent = currentSpent + COST;
            setSpent(newSpent);

            // Log to Database using Utils
            await logJobToDatabase(room, requestData, result.url);

            // Send Result back
            const msg = {
                type: 'GENERATION_COMPLETE',
                data: {
                    targetId: requestData.senderId,
                    processorName: room.peers[room.clientId]?.username || currentUser?.username || "Unknown",
                    success: true,
                    imageUrl: result.url
                }
            };
            room.send(msg);
            if (msg.data.targetId === room.clientId) handleMessage(msg);

        } catch (err) {
            console.error(err);
            const msg = {
                type: 'GENERATION_COMPLETE',
                data: {
                    targetId: requestData.senderId,
                    processorName: room.peers[room.clientId]?.username || currentUser?.username || "Unknown",
                    success: false,
                    error: "Generation failed."
                }
            };
            room.send(msg);
            if (msg.data.targetId === room.clientId) handleMessage(msg);
        } finally {
            room.updatePresence({
                ...room.presence[room.clientId],
                status: 'idle',
            });
        }
    };

    const fetchLeaderboard = async () => {
        const records = await room.collection('processor_stats_v1').getList();
        // Sort by total_processed descending
        const sorted = records.sort((a, b) => (b.total_processed || 0) - (a.total_processed || 0));
        setLeaderboard(sorted);
    };

    // --- Client / Sender Logic ---

    const sendRequest = async (targetPeerId) => {
        if (!prompt) return alert("Please enter a prompt");

        setProcessingPeerId(targetPeerId);
        setStatusMsg("Uploading assets...");
        setResultImage(null);

        let sourceImageUrl = null;
        if (selectedImage) {
            try {
                sourceImageUrl = await websim.upload(selectedImage);
            } catch (e) {
                setStatusMsg("Upload failed.");
                setProcessingPeerId(null);
                return;
            }
        }

        const targetName = (targetPeerId === room.clientId) ? "Myself" : (peers[targetPeerId]?.username || "Peer");
        setStatusMsg(`Waiting for ${targetName}...`);

        const msg = {
            type: 'REQUEST_GENERATION',
            data: {
                targetId: targetPeerId,
                senderId: room.clientId,
                senderName: currentUser.username,
                prompt: prompt,
                sourceImageUrl: sourceImageUrl
            }
        };

        room.send(msg);
        if (targetPeerId === room.clientId) {
            handleMessage(msg);
        }
    };

    const handleFileChange = (e) => {
        if (e.target.files && e.target.files[0]) {
            setSelectedImage(e.target.files[0]);
        }
    };

    return (
        <div className="flex flex-col h-full max-w-md mx-auto w-full bg-slate-900 shadow-2xl relative">
            <Header tab={tab} setTab={setTab} />

            {/* Main Content Area */}
            <main className="flex-1 overflow-y-auto p-4 scroll-container relative">

                {tab === 'settings' && (
                    <SettingsTab 
                        currentUser={currentUser}
                        threshold={threshold}
                        setThreshold={setThreshold}
                        spent={spent}
                        setSpent={setSpent}
                    />
                )}

                {tab === 'leaderboard' && (
                    <LeaderboardTab leaderboard={leaderboard} />
                )}

                {tab === 'generate' && (
                    <GenerateTab 
                        prompt={prompt}
                        setPrompt={setPrompt}
                        selectedImage={selectedImage}
                        handleFileChange={handleFileChange}
                        setSelectedImage={setSelectedImage}
                        resultImage={resultImage}
                        processingPeerId={processingPeerId}
                        statusMsg={statusMsg}
                        peers={peers}
                        currentUser={currentUser}
                        room={room}
                        sendRequest={sendRequest}
                        presence={presence}
                    />
                )}
            </main>
        </div>
    );
};

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);